wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705344905.92425
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      3:
      - 23
      4: 3.11.7
      5: 0.16.2
      6: 4.36.2
      8:
      - 5
      13: linux-x86_64
trl_ppo_trainer_config:
  desc: null
  value:
    exp_name: main
    seed: 42
    log_with: wandb
    task_name: null
    model_name: augustocsc/gpt-base
    query_dataset: null
    reward_model: null
    remove_unused_columns: true
    tracker_project_name: trl
    steps: 20000
    learning_rate: 1.5e-05
    adap_kl_ctrl: true
    init_kl_coef: 0.2
    kl_penalty: kl
    target: 6
    horizon: 10000
    gamma: 1
    lam: 0.95
    cliprange: 0.2
    cliprange_value: 0.2
    vf_coef: 0.1
    batch_size: 128
    forward_batch_size: null
    mini_batch_size: 16
    gradient_accumulation_steps: 1
    world_size: 1
    ppo_epochs: 4
    max_grad_norm: null
    optimize_cuda_cache: null
    optimize_device_cache: false
    early_stopping: false
    target_kl: 1
    compare_steps: 1
    ratio_threshold: 10.0
    use_score_scaling: false
    use_score_norm: false
    score_clip: null
    whiten_rewards: false
    is_encoder_decoder: false
    is_peft_model: false
    backward_batch_size: 16
    global_backward_batch_size: 16
    global_batch_size: 128
    total_ppo_epochs: 157
